model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    log_every_t: 100
    timesteps: 1000
    loss_type: l2
    first_stage_key: data
    cond_stage_key: label
    image_size: 64
    channels: 3
    concat_mode: true
    cond_stage_trainable: true
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 6
        out_channels: 3
        model_channels: 160
        attention_resolutions:
        - 16
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 2
        - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        ckpt_path: models/first_stage_models/vq-f4/model.ckpt
        embed_dim: 3
        n_embed: 8192
        monitor: val/rec_loss
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.swin_transformer_3d.SwinTransformer3D
      params:
        patch_size: 
        - 2 # Sequence axis
        - 4 # Height axis
        - 4 # Width axis
        in_chans: 3
        embed_dim: 96
        depths:
        - 8
        num_heads: 
        - 3
        window_size: 
        - 2
        - 7
        - 7
        use_checkpoint: true
        sequence_to_image: attention
        output_type: image
        n_embed: 3

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 2
    wrap: false
    train:
      target: ldm.data.siar.SIAR
      params:
        root: ../data/SIAR
        set_type: train
        resolution: 256
        downscale_f: 4
        max_sequence_size: 10
    validation:
      target: ldm.data.siar.SIAR
      params:
        root: ../data/SIAR
        set_type: val
        resolution: 256
        downscale_f: 4
        max_sequence_size: 10
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        max_images: 4
        batch_frequency: 800
        log_on_batch_idx: false
        increase_log_steps: false
        log_images_kwargs:
          inpaint: false
          plot_progressive_rows: false
  trainer:
    accumulate_grad_batches: 2