model:
  base_learning_rate: 0.0001
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: data
    cond_stage_key: label
    image_size: 64
    channels: 3
    cond_stage_trainable: false
    monitor: val/loss
    use_ema: False
    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 192
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 5
        num_heads: 8
    
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        monitor: val/rec_loss
        embed_dim: 3
        ckpt_path: "models/first_stage_models/kl-f4/model.ckpt"
        ddconfig:
          double_z: true
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: ldm.modules.losses.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 1.0e-06
            disc_weight: 0.5
    
    cond_stage_config: "__is_unconditional__"
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 4
    wrap: false
    train:
      target: ldm.data.siar.SIAR
      params:
        root: ../data/SIAR
        set_type: train
        resolution: 256
    validation:
      target: ldm.data.siar.SIAR
      params:
        root: ../data/SIAR
        set_type: val
        resolution: 256

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        max_images: 4
        batch_frequency: 750
        log_on_batch_idx: False
        increase_log_steps: False
        log_images_kwargs:
          inpaint: False
          plot_progressive_rows: False
  trainer:
    accumulate_grad_batches: 4