model:
  base_learning_rate: 2.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: data
    cond_stage_key: label
    image_size: 64
    channels: 3
    cond_stage_trainable: false
    monitor: val/loss
    use_ema: false
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 96
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 1
        channel_mult:
        - 1
        - 2
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        monitor: val/rec_loss
        embed_dim: 3
        ckpt_path: models/first_stage_models/kl-f4/model.ckpt
        ddconfig:
          double_z: true
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 1
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: ldm.modules.losses.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 1.0e-06
            disc_weight: 0.5
    cond_stage_config: __is_unconditional__
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 2
    wrap: false
    train:
      target: ldm.data.siar.SIAR
      params:
        root: ../data/SIARmini
        set_type: train
        resolution: 256
        max_sequence_size: 1
    validation:
      target: ldm.data.siar.SIAR
      params:
        root: ../data/SIARmini
        set_type: val
        resolution: 256
        max_sequence_size: 1
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        max_images: 4
        batch_frequency: 100
        log_on_batch_idx: false
        increase_log_steps: false
        log_images_kwargs:
          inpaint: false
          plot_progressive_rows: false
  trainer:
    accumulate_grad_batches: 2